# Generated by Django 5.1.1 on 2024-09-18 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('server', models.CharField(choices=[('01', 'Adamantoise'), ('02', 'Aegis'), ('03', 'Alexander'), ('04', 'Anima'), ('05', 'Asura'), ('06', 'Atomos'), ('07', 'Bahamut'), ('08', 'Balmung'), ('09', 'Behemoth'), ('10', 'Belias'), ('11', 'Brynhildr'), ('12', 'Cactuar'), ('13', 'Carbuncle'), ('14', 'Cerberus'), ('15', 'Chocobo'), ('16', 'Coeurl'), ('17', 'Diabolos'), ('18', 'Durandal'), ('19', 'Excalibur'), ('20', 'Exodus'), ('21', 'Faerie'), ('22', 'Famfrit'), ('23', 'Fenrir'), ('24', 'Garuda'), ('25', 'Gilgamesh'), ('26', 'Goblin'), ('27', 'Gungnir'), ('28', 'Hades'), ('29', 'Hyperion'), ('30', 'Ifrit'), ('31', 'Ixion'), ('32', 'Jenova'), ('33', 'Kujata'), ('34', 'Lamia'), ('35', 'Leviathan'), ('36', 'Lich'), ('37', 'Louisoix'), ('38', 'Malboro'), ('39', 'Mandragora'), ('40', 'Masamune'), ('41', 'Mateus'), ('42', 'Midgardsormr'), ('43', 'Moogle'), ('44', 'Odin'), ('45', 'Omega'), ('46', 'Pandaemonium'), ('47', 'Phoenix'), ('48', 'Ragnarok'), ('49', 'Ramuh'), ('50', 'Ridill'), ('51', 'Sargatanas'), ('52', 'Shinryu'), ('53', 'Shiva'), ('54', 'Siren'), ('55', 'Tiamat'), ('56', 'Titan'), ('57', 'Tonberry'), ('58', 'Typhon'), ('59', 'Ultima'), ('60', 'Ultros'), ('61', 'Unicorn'), ('62', 'Valefor'), ('63', 'Yojimbo'), ('64', 'Zalera'), ('65', 'Zeromus'), ('66', 'Zodiark'), ('67', 'Spriggan'), ('68', 'Twintania'), ('69', 'Bismarck'), ('70', 'Ravana'), ('71', 'Sephirot'), ('72', 'Sophia'), ('73', 'Zurvan'), ('74', 'Halicarnassus'), ('75', 'Maduin'), ('76', 'Marilith'), ('77', 'Seraph'), ('78', 'Alpha'), ('79', 'Phantom'), ('80', 'Raiden'), ('81', 'Sagittarius')], default='01', max_length=2)),
                ('role', models.CharField(choices=[('T', 'Tank'), ('H', 'Healer'), ('D', 'DPS')], default='T', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PLD', 'Paladin'), ('WAR', 'Warrior'), ('DRK', 'Dark Knight'), ('GNB', 'Gunbreaker'), ('WHM', 'White Mage'), ('SCH', 'Scholar'), ('AST', 'Astrologian'), ('SGE', 'Sage'), ('MNK', 'Monk'), ('DRG', 'Dragoon'), ('NIN', 'Ninja'), ('SAM', 'Samurai'), ('RPR', 'Reaper'), ('VPR', 'Viper'), ('BRD', 'Bard'), ('MCH', 'Machinist'), ('DNC', 'Dancer'), ('BLM', 'Black Mage'), ('SMN', 'Summoner'), ('RDM', 'Red Mage'), ('PCT', 'Pictomancer')], default='PLD', max_length=3)),
                ('description', models.TextField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.player')),
            ],
        ),
    ]
