# Generated by Django 5.1.1 on 2024-09-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_player_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_img',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
