# Generated by Django 5.1.1 on 2024-09-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_player_player_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
